
This is an Ionic5 / Angled app under construction that has the Ionic5 components organized into pages, with the aim of helping programmers
in application development in Ionic5/angular !

To start you should have cordova ,node.js , java installed on your machine (be careful with the latest version, you will probably have to downgrade)

Go to src/app/ here you will find a variety of components with notes that will help with programming !