Este é um app em Ionic5 /angular em construção  que possui os componentes do Ionic5 organizado em paginas , com o objetivo de ajudar programadores
no desenvolvimento de  aplicativos em Ionic5/angular !

Para iniciar você deve ter instaldo em sua máquina o cordova ,node.js , java (cuidado com a version mais atual, provavelmente terá que fazer dowgrade0)

Vá em src/app/   aqui encontrá um variedade de componentes com observaçoes que ajudará na programação !